import 'package:get/get.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys {
    return {
      "en_US": {
        "language": "English",
        "login": "Login",
        "Login With Password": "Login With Password",
        "payment_confirm": "your transaction is under process kindly wait for a while",
        "forget_password": "Forgot Password",
        "total_km_distance": "Total km Distance",
        "otp": "OTP",
        "new_password": "New Password",
        "confirm_new_password": "Confirm New Password",
        "submit": "Submit",
        "please_enter_otp": "Please enter OTP",
        "wrong_otp": "Wrong OTP!",
        "please_enter_password": "Please enter password",
        "password_length": "Password length must be between 6–15 characters.",
        "password_should_be_same": "Password should be same",
        "welcome_back": "Welcome Back",
        "email": "Email",
        "password": "Password",
        "forget_password?": "Forget Password?",
        "log_in": "Log In",
        "don't_have_an_account?": "Don't have an account?",
        "register": "Register",
        "enter_phone_number_to_continue": "Enter phone number to continue",
        "continue": "Continue",
        "please_enter_valid_otp": "Please enter valid otp In",
        "didn`t_get_the_otp": "Didn`t get the OTP",
        "resend_otp": "Resend OTP",
        "vehicle_details": "Vehicle Details",
        "phone": "Phone",
        "please_enter_your_mobile_number": "Please enter your mobile number.",
        "check_fare": "Check Fare",
        "Book_a_ride": "Book a ride",
        "Schedule_a_ride": "Schedule a ride",
        "sign_up": "Sign Up",
        "or_continue_with": "Or Continue with",
        "create_account": "Create\nAccount",
        "create_an_account": "Create an Account",
        "first_name": "First Name",
        "last_name": "Last Name",
        "next": "Next",

        "service_type": "Service Type",
        "please_choose_a_service_type": "Please choose a service type",
        "confirm_password": "Confirm Password",
        "referral_code": "Referral Code",
        "referral_code_(Optional)": "Referral Code (Optional)",
        "i_have_read_and_agreed_the_terms_and_Conditions":
            "I have read and agreed the Terms and\nConditions.",
        "document": "Document",
        "data_not_found": "Data not found...",
        "edit": "Edit",
        "add": "Add",
        "add_document": "Add Document",
        "earnings": "Earnings",
        "today's_completed_target": "Today's Completed Target",
        "total_earning": "Total Earning",
        "km": "KM",
        "total_trips": "Total Trips",
        "time": "Time",
        "distance": "Distance",
        "amount": "Amount",
        "help": "Help",
        "support": "Support",
        "call": "Call",
        "message": "Message",
        "our_team_persons_will_contact_you_soon!":
            "Our team persons will contact you soon!",
        "instant_ride": "Instant Ride",
        "done": "Done",
        "phone_number": "Phone Number",
        "where_to": "Where To",
        "pick_from_map": "Pick From Map",
        "location_permissions_are_denied": "Location permissions are denied",
        "allow": "Allow",
        "invite_friend": "Invite Friend",
        "your_referral_code": "Your Referral Code",
        "choose_one": "choose one",
        "referral_count:": "Referral Count:",
        "referral_amount:": "Referral Amount:",
        "nio_demo": "Nio Demo",
        "from_to": "From To",
        "round_trip": "Round Trip",
        "notification_manager": "Notification Manager",
        "you_don't_have_any_notification": "You don't have any notification",
        "offers": "Offers",
        "cpd01": "CPD01",
        "10%_off_max_discount_is_50": "10% Off Max discount is 50",
        "valid_till_:_13,June_2021": "valid Till : 13,June 2021",
        "use_code": "Use Code",
        "passbook": "passbook",
        "no_wallet_history": "No Wallet History",
        "past_trip_details": "Past Trip Details",
        "pay_via": "Pay via",
        "comments": "Comments",
        "no_comments": "No Comments",
        "view_receipt": "View Receipt",
        "dispute": "Dispute",
        "you": "You",
        "driver_unprofessional": "Driver Unprofessional",
        "open": "OPEN",
        "payment": "Payment",
        "payment_options": "Payment Options",
        "by_cash": "By Cash",
        "profile": "Profile",
        "service": "Service",
        "looking_to_change_password": "Looking to change password",
        "save": "Save",
        "setting": "Setting",
        "choose_language": "Choose Language",
        "summary": "Summary",
        "total_no_of_rides": "Total No. Of Rides",
        "revenue": "Revenue",
        "no._of_scheduled_rides": "No.Of Scheduled Rides",
        "cancelled_ride": "Cancelled Ride",
        "wallet": "Wallet",
        "your_wallet_amount": "Your Wallet Amount",
        "transaction_id": "Transaction Id",
        "date": "Date",
        "your_trips": "Your Trips",
        "add_toll_charge": "Add Toll Charge",
        "add_Toll": "Add Toll",
        "dismiss": "Dismiss",
        "please_enter_valid_amount": "Please enter valid amount",
        "please_confirm_the_address": "",
        "picked_up_location": "Picked up Location",
        "drop_location": "Drop Location",
        "confirm": "Confirm",
        "otp_verification": "OTP Verification",
        "cancel": "Cancel",
        "reason_for_canceling": "Reason or canceling",
        "something_went_wrong": "Something went wrong...",
        "scan_the_qr_to_fetch_mobile_number":
            "Scan the QR to fetch mobile number",
        "otp_verified": "OTP Verified!",
        "invoice": "Invoice",
        "booking_id": "Booking ID",
        "time_taken": "Time Taken",
        "base_fare": "Base Fare",
        "time_fare": "Time Fare",
        "tax": "Tax",
        "toll_charges": "Toll Charges",
        "round_off": "Round off",
        "total": "Total",
        "payable": "Payable",
        "close": "Close",
        "time_remaining": "Time Remaining",
        "pick_up_location": "Pick Up Location",
        "decline": "Decline",
        "accept": "Accept",
        "confirm_payment": "Confirm Payment",
        "no_data_found": "No data found..",
        "ratings_your_trip_with": "Rate's your trip with",
        "write_your_comment": "Write your comment",
        "are_you_sure_want_to_cancel_this_request":
            "Are you sure want to Cancel this request?",
        "arrived": "Arrived",
        "picked_up": "Picked Up",
        "arrived_location": "Arrived Location",
        "waiting_time": "Waiting Time",
        "tap_when_dropped": "TAP WHEN DROPPED",
        "hey_checkout_this_app": "Hey Checkout this app,Mozlit Driver",
        "are_you_sure_want_to_logout": "Are you sure want to logout?",
        "no": "NO",
        "yes": "Yes",
        "add_card_for_payments": "Add card for payments",
        "card_number": "Card Number",
        "mozilit_driver": "Mozilit Driver",
        "expiration_date": "Expiration Date",
        "cvv": "CVV",
        "add_card": "Add Card",
        "please_insert_valid_expiry_date": "Please insert valid expiry date",
        "change_password": "Change\nPassword",
        "current_password": "Current Password",
        "terms_Condition": "Terms & Condition Password",
        "chat": "Chat",
        "loading": "Loading...",
        "type_something_here": "Type Something Here",
        "swipe_to_online": "Swipe to online",
        "swipe_to_offline": "Swipe to offline",
        "could_not_launch": "Could not launch",
        "qr_scan": "Qr Scan",
        "your_tips": "Your Tips",
        "earning": "Earning",
        "card": "Card",
        "share": "Share",
        "logout": "Logout",
        "ride_updated": "Ride Updated",
        "hi": "Hi",
        "past_rides": "Past Rides",
        "account": "Account",
        "source": "Source",
        "destination": "Destination",
        "user_arrogant_and_rude": "User arrogant and rude",
        "charging_stations": "Charging Stations",
        "give_feedback": "Give Feedback",
        "terms_and_conditions": "Terms And Conditions",
        "privacy_policy": "Privacy Policy",
        "our_you_soon!": "Our team person will contact you soon!",
        "add_money": "Add Money",
        "add_amount": "Add Amount",
        "together": "Together, we\'re growing\nStronger and further",
        "refer_now_and_earn": "Refer Now and Earn",
        "or": "Or",
        "share_your_link_via": "Share your link via",
        "spread_the_word": "Spread the word, And we will\nreward you",
        "get INR 100 in your Mozilit wallet for every friend you refer":
            "Get INR 100 in your Mozilit wallet for every friend you refer",
        "refCode:": "Referral Code:",
        "delete_account": "Delete\nAccount",
        "trip_details": "Trip Details",
        "start_ride": "Start Ride",
        "end_ride": "End Ride",
        "feedback_for_the_user": "Feedback for the user",
        "Please_type_the_verification_code_sent_to_your":
            "Please type the verification code sent to your",
        "mobile_number": " Mobile Number",
        "your_email": " Email",
        "verification_code": "Verification Code",
        "forgot_password": "Forgot Password",
        "Driver_Registration": "Driver Registration",
        "Vehicle_Registration": "Vehicle Registration",
        "did_get_the_OTP": "didn`t Get The OTP?",
        "look_for_new_ride": "Look For New Ride",
        "car_type": "Car Type",
        "car_name": "Car Name",
        "car_color": "Car Colour",
        "car_model": "Car Model",
        "car_number": "Car Number",
        "please_enter_amount": "Please enter amount",
        "Please_enter_more_when_amount": "Please_enter_more_when_amount",
        "sorry_for_inconvenience_time_Our_partner": "Sorry for inconvience time, Our partner or busy. Please try after some time",
        "We_are_searching_for_new_driver_please_wait_till_we_get_the_new_driver": "We are searching for new driver, please wait till we get the new driver.",
        "have_a_nice_day":"Have a nice day",
        "Taxi service type": "Taxi service type",
        "Delivery service type": "Delivery service type",
        "TAXI": "TAXI",
        "DELIVERY": "DELIVERY",
        "package_details": "Package details",
        "congratulations": "Congratulations",
        "you_have_successfully": "You have successfully",
        "completed": "completed ",
        "trips_with": " trips with",
        "touk_touk": "Touk Touk",
        "you_are_now_a_verified": "You are now a verified driver on Touk Touk",
        "All_users_will": "All users will be able to see the",
        "verification_green_tick": "Verification green tick ",
        "in_front_of_your_name": "in front of your name",
        "keep_Riding": "Keep Riding with us, We value your trust placed on us",
        "taxi": 'taxi',
        "delivery": "delivery"

      },
      "hi_IN": {
        "have_a_nice_day":"आपका दिन शुभ हो",
        "Login With Password": "पासवर्ड से लॉगिन करें",
        "vehicle_details": "वाहन की सूचना",
        "sorry_for_inconvenience_time_Our_partner": "असुविधा के समय के लिए खेद है, हमारे साथी या व्यस्त। कृपया कुछ देर बाद प्रयास करें",
        "car_color": "कार का रंग",
        "please_enter_amount": "कृपया राशि दर्ज करें",
        "Please_enter_more_when_amount": "कृपया अधिक कब दर्ज करें",
        "We_are_searching_for_new_driver_please_wait_till_we_get_the_new_driver": "हम नए ड्राइवर की तलाश कर रहे हैं, कृपया तब तक प्रतीक्षा करें जब तक हमें नया ड्राइवर नहीं मिल जाता।",
        "look_for_new_ride": "नई सवारी की तलाश करें",
        "payment_confirm": "आपका लेनदेन प्रक्रियाधीन है कृपया थोड़ी देर प्रतीक्षा करें",
        "Driver_Registration": "चालक पंजीकरण",
        "Vehicle_Registration": "वाहन पंजीकरण",
        "next": "अगला",
        "language": "हिन्दी",
        "forgot_password": " पासवर्ड भूल गए ",
        "total_km_distance": "कुल किमी दूरी",
        "otp": " ओटीपी ",
        "new_password": " नया पासवर्ड ",
        "confirm_new_password": " नए पासवर्ड की पुष्टि करें ",
        "submit": " प्रस्तुत करना ",
        "please_enter_otp": " कृपया ओटीपी दर्ज करें ",
        "wrong_otp": " गलत ओटीपी ",
        "please_enter_password": " कृप्या पास्वर्ड भरो ",
        "password_length": " पासवर्ड की लंबाई 6-15 अक्षरों के बीच होनी चाहिए.",
        "password_should_be_same": " पासवर्ड समान होना चाहिए ",
        "welcome_back": " वापसी पर स्वागत है ",
        "email": " ईमेल ",
        "password": " पासवर्ड ",
        "log_in": " लॉग इन करें ",
        "don't_have_an_account?": " खाता नहीं है?",
        "register": " पंजीकरण करवाना ",
        "verification_code": " पुष्टि संख्या ",
        "continue": " जारी रखना ",
        "please_enter_valid_otp": " कृपया मान्य ओटीपी दर्ज करें ",
        "didn`t_get_the_OTP": " ओटीपी नहीं मिला ",
        "resend_OTP": " ओटीपी पुनः भेजें ",
        "enter_phone": " जारी रखने के लिए फ़ोन नंबर दर्ज करें ",
        "phone": " फ़ोन ",
        "please_number.": " अपना मोबाइल नंबर दर्ज करें.",
        "check_fare": " किराया जांचें ",
        "Book_a_ride": "सवारी बुक करें",
        "Schedule_a_ride": "एक राइड शेड्यूल करें",
        "sign_up": " साइन अप करें ",
        "Or_continue_with": " या साथ जारी रखें ",
        "create_account": " खाता बनाएं ",
        "create_an_account": " खाता बनाएं ",
        "first_name": " पहला नाम ",
        "last_name": " उपनाम ",
        "car_model": " कार के मॉडल ",
        "car_number": " कार का नबंर ",
        "did_get_the_OTP": "नहीं मिला ओटॉप? ",
        "service_type": " सेवा प्रकार ",
        "please_choose_a_service_type": " कृपया एक सेवा प्रकार चुनें ",
        "confirm_password": " पासवर्ड की पुष्टि कीजिये ",
        "referral_code": " रेफरल कोड ",
        "referral_code_(Optional)": " रेफरल कोड (वैकल्पिक)",
        "i_have_read_and_agreed_the_terms_and_Conditions":
            " मैंने नियम और शर्तें पढ़ ली हैं और उनसे सहमत हूं.",
        "document": "दस्तावेज़",
        "data_not_found": " डेटा नहीं मिला...",
        "edit": " संपादन करना ",
        "add": " जोड़ें ",
        "add_document": " दस्तावेज़ जोड़ें ",
        "earnings": "आय",
        "today's_completed_target": " आज का लक्ष्य पूरा ",
        "total_earning": " कुल कमाई ",
        "km": "KM",
        "total_trips": " कुल यात्राएं ",
        "time": " समय ",
        "distance": " दूरी ",
        "amount": " राशि ",
        "help": "मदद",
        "support": " सहायता ",
        "call": " बुलाना ",
        "message": " संदेश ",
        "our_team_persons_will_contact_you_soon!":
            " हमारी टीम के लोग जल्द ही आपसे संपर्क करेंगे!",
        "instant_ride": "तत्काल सवारी",
        "done": " पूर्ण ",
        "phone_number": " फ़ोन नंबर ",
        "where_to": " जहां ",
        "pick_from_map": " मानचित्र से चुनें ",
        "location_permissions_are_denied": " स्थान अनुमतियां अस्वीकृत हैं ",
        "allow": " अनुमति देना ",
        "invite_friend": "मित्र को न्योता ",
        "your_referral_code": "आपका रेफरल कोड ",
        "choose_one": " एक का चयन ",
        "referral_count:": "रेफरल काउंट:",
        "referral_amount:": " रेफरल राशि:",
        "nio_demo": " निओ डेमो ",
        "from_to": " से ",
        "round_trip": " राउंड ट्रिप ",
        "notification_manager": " अधिसूचना प्रबंधक ",
        "you_don't_have_any_notification": " आपके पास कोई सूचना नहीं है ",
        "offers": " ऑफर ",
        "cpd01": "CPD01",
        "10%_off_max_discount_is_50": "अधिकतम छूट पर 10% की छूट 50 है",
        "valid_till_:_13,June_2021": " तक वैध: 13, जून 2021",
        "use_code": " कोड का प्रयोग करें ",
        "passbook": "पासवृकk",
        "no_wallet_history": " कोई बटुआ इतिहास नहीं ",
        "past_trip_details": " पिछली यात्रा का विवरण ",
        "pay_via": " माध्यम से भुगतान करें ",
        "comments": " टिप्पणियाँ ",
        "no_comments": " कोई टिप्पणी नहीं ",
        "view_receipt": " रसीद देखें ",
        "dispute": " विवाद ",
        "you": " आप ",
        "driver_unprofessional": " चालक अव्यवसायिक ",
        "open": " खोलना ",
        "payment": " भुगतान ",
        "payment_options": " भुगतान विकल्प ",
        "by_cash": " नकद द्वारा ",
        "profile": " प्रोफ़ाइल ",
        "service": " सेवा ",
        "looking_to_change_password": " पासवर्ड बदलना चाह रहे हैं ",
        "save": " बचाना ",
        "setting": " स्थापना ",
        "choose_language": "भाषा चुनें",
        "summary": " सारांश ",
        "total_no_of_rides": " सवारी की कुल संख्या ",
        "revenue": " आय ",
        "no._of_scheduled_rides": " अनुसूचित सवारी की संख्या ",
        "cancelled_ride": " रद्द की गई सवारी ",
        "wallet": "बटुआ",
        "your_wallet_amount": " आपकी वॉलेट राशि ",
        "transaction_id": "लेनदेन आईडी ",
        "date": " दिनांक ",
        "your_trips": " आपकी यात्राएं ",
        "add_toll_charge": " टोल चार्ज जोड़ें ",
        "add_Toll": " टोल जोड़ें ",
        "dismiss": " नकार देना ",
        "please_enter_valid_amount": " कृपया मान्य राशि दर्ज करें ",
        "please_confirm_the_address": " कृपया पते की पुष्टि करें ",
        "picked_up_location": " उठाया स्थान ",
        "drop_location": " ड्रॉप स्थान ",
        "confirm": " पुष्टि करें ",
        "otp_verification": " ओटीपी सत्यापन ",
        "cancel": " रद्द करना ",
        "reason_for_canceling": " कारण या रद्द करना ",
        "something_went_wrong": " कुछ गलत हो गया...",
        "scan_the_qr_to_fetch_mobile_number":
            " मोबाइल नंबर प्राप्त करने के लिए क्यूआर स्कैन करें ",
        "otp_verified": " ओटीपी सत्यापित!",
        "invoice": " इनवॉइस ",
        "booking_id": " बुकिंग आईडी ",
        "time_taken": " समय लिया ",
        "base_fare": " बुनियादी भाड़ा ",
        "time_fare": " समय किराया ",
        "tax": " कर ",
        "toll_charges": " टोल शुल्क ",
        "round_off": " पूर्णांक करना ",
        "total": " कुल ",
        "payable": " देय ",
        "close": " बंद करना ",
        "time_remaining": " शेष समय ",
        "pick_up_location": " उठाने की जगह ",
        "decline": " पतन ",
        "accept": " स्वीकार करना ",
        "confirm_payment": " भुगतान की पुष्टि करें ",
        "no_data_found": " कोई डेटा नहीं मिला..",
        "ratings_your_trip_with": " के साथ अपनी यात्रा का मूल्यांकन करें ",
        "write_your_comment": " अपनी टिप्पणी लिखें ",
        "are_you_sure_want_to_cancel_this_request":
            " क्या आप वाकई इस अनुरोध को रद्द करना चाहते हैं?",
        "arrived": " पहुंच गए ",
        "picked_up": " उठाया ",
        "arrived_location": " पहुंचने का स्थान ",
        "waiting_time": " इंतजार का समय ",
        "tap_when_dropped": " पहुंचने पर टैप करें ",
        "hey_checkout_this_app": " अरे इस ऐप को चेकआउट करें ",
        "are_you_sure_want_to_logout": " क्या आप वाकई लॉग आउट करना चाहते हैं?",
        "no": " ना ",
        "yes": " हाँ ",
        "add_card_for_payments": " भुगतान के लिए कार्ड जोड़ें ",
        "card_number": " कार्ड नंबर ",
        "mozilit_driver": " ईटीओ चालक ",
        "expiration_date": " समाप्ति तिथि ",
        "cvv": "CVV",
        "add_card": " कार्ड जोड़ें ",
        "please_insert_valid_expiry_date": " कृपया मान्य समाप्ति तिथि डालें ",
        "change_password": " पासवर्ड\nबदलें ",
        "current_password": " वर्तमान पासवर्ड ",
        "terms_Condition": " नियम और शर्त पासवर्ड ",
        "terms_and_Condition": " नियम व शर्त ",
        "chat": " बात करना ",
        "loading": " लोड हो रहा है...",
        "type_something_here": " यहाँ कुछ टाइप करें ",
        "swipe_to_online": " ऑनलाइन जाने के लिए स्वाइप करें ",
        "swipe_to_offline": " ऑफ़लाइन जाने के लिए स्वाइप करें ",
        "could_not_launch": "लॉन्च नहीं कर सका ",
        "qr_scan": "क्यूआर स्कैन ",
        "your_tips": "आपकी युक्तियाँ ",
        "earning": "कमाई ",
        "card": "कार्ड ",
        "share": " ेयर करना ",
        "logout": "लॉग आउट",
        "hi": "नमस्ते",
        "past_rides": "पिछली सवारी",
        "account": "खाता",
        "source": "स्रोत",
        "destination": "गंतव्य",
        "user_arrogant_and_rude": "उपयोगकर्ता अभिमानी और असभ्य",
        "charging_stations": "चार्जिंग स्टेशन",
        "give_feedback": "प्रतिक्रिया दें",
        "terms_and_conditions": "नियम और शर्तें",
        "privacy_policy": "गोपनीयता नीति",
        "our_you_soon!": "हमारी टीम के सदस्य जल्द ही आपसे संपर्क करेंगे!",
        "add_money": "पैसे जोड़ें",
        "add_amount": "राशि जोड़ें",
        "together": "साथ में, हम\nमजबूत और आगे बढ़ रहे हैं",
        "refer_now_and_earn": "अभी देखें और कमाएं",
        "or": "या",
        "share_your_link_via": "के माध्यम से अपना लिंक साझा करें",
        "spread_the_word": "प्रचार करें, और हम आपको\nपुरस्कृत करेंगे",
        "get INR 100 in your Mozilit wallet for every friend you refer":
            "आपके द्वारा संदर्भित प्रत्येक मित्र के लिए अपने Mozilit वॉलेट में INR 100 प्राप्त करें",
        "refCode:": "रेफरल कोड:",
        "car_type": "कार प्रकार",
        "car_name": "कार का नाम",
        "delete_account": "खाता\nहटा दो",
        "trip_details": "यात्रा विवरण",
        "start_ride": "राइड शुरू करें",
        "end_ride": "सवारी समाप्त करें",
        "feedback_for_the_user": "उपयोगकर्ता के लिए प्रतिक्रिया",
        "Please_type_the_verification_code_sent_to_your":
            "कृपया आपके पर भेजा गया सत्यापन कोड टाइप करें",
        "mobile_number": "मोबाइल नंबर",
        "your_email": " ईमेल"
      },
      "nl_NL": {
        "language": "Dutch",
        "Login With Password": "Inloggen met wachtwoord",
        "forgot_password": "Wachtwoord vergeten",
        "otp": "OTP",
        "new_password": "nieuw paswoord",
        "confirm_new_password": "Bevestig nieuw wachtwoord",
        "submit": "Indienen",
        "please_enter_otp": "Voer alstublieft OTP in",
        "wrong_otp": "Verkeerde OTP!",
        "please_enter_password": "Voer wachtwoord in alstublieft",
        "password_length":
            "De lengte van het wachtwoord moet tussen 6-15 tekens zijn.",
        "password_should_be_same": "Wachtwoord moet hetzelfde zijn",
        "welcome_back": "Welkom\nterug",
        "email": "E-mail",
        "password": "Wachtwoord",
        "forget_password": "Wachtwoord vergeten?",
        "log_in": "Log In",
        "don't_have_an_account?": "Don't have an account?",
        "register": "Register",
        "enter_phone_number_to_continue":
            "Voer telefoonnummer in om door te gaan",
        "please_type_the_verification_code_sent_to_your":
            "Typ de verificatiecode a.u.b.\nverzonden naar uw",
        "continue": "Doorgaan",
        "please_enter_valid_otp": "Voer een geldige otp In . in",
        "didn`t_get_the_otp": "Ik heb de OTP niet gekregen",
        "resend_otp": "OTP OPNIEUW VERZENDEN",
        "phone": "Telefoon",
        "please_enter_your_mobile_number":
            "Voer alstublieft uw mobiele nummer in.",
        "check_are": "Controleer tarief",
        "sign_up": "Aanmelden",
        "or_continue_with": "Of Ga verder met",
        "create_account": "Creëren\nAccount",
        "firstname": "Voornaam",
        "Lastname": "Achternaam",
        "car_model": "Auto model",
        "car_number": "Auto Number",
        "service_type": "Dienst Type",
        "please_choose_a_service_type": "Kies een servicetype",
        "confirm_password": "bevestig wachtwoord",
        "referral_code": "Verwijzingscode:",
        "referral_code_(Optional)": "Verwijzingscode (optioneel)",
        "i_have_read_and_agreed_the_terms_and_Conditions":
            "Ik heb de voorwaarden gelezen en ga ermee akkoord en\nConditie.",
        "document": "Document",
        "data_not_found": "Data niet gevonden...",
        "edit": "Bewerk",
        "add_document": "Document toevoegen",
        "earnings": "Inkomsten",
        "today's_completed_target": "Het voltooide doel van vandaag",
        "total_earning": "Totale winst",
        "km": "KM",
        "total_trips": "Totaal aantal reizen",
        "time": "Tijd",
        "distance": "Afstand",
        "amount": "Hoeveelheid",
        "help": "Helpen",
        "support": "Steun",
        "call": "Telefoongesprek",
        "message": "Bericht",
        "our_team_persons_will_contact_you_soon!":
            "Onze teamleden nemen spoedig contact met u op!",
        "instant_ride": "Directe rit",
        "done": "Gedaan",
        "phone_number": "Telefoonnummer",
        "where_to": "Waarheen",
        "pick_from_map": "Kies uit kaart",
        "location_permissions_are_denied": "Locatierechten zijn geweigerd",
        "allow": "Toestaan",
        "invite_friend": "Nodig een vriend uit",
        "your_referral_code": "Uw verwijzingscode",
        "choose_one": "kies er een",
        "referral_count_:": "Aantal verwijzingen:",
        "referral_amount:": "Verwijzingsbedrag:",
        "nio_demo": "Nio-demo",
        "from_to": "Van naar",
        "round_trip": "Rondvaart",
        "notification_manager": "Meldingsmanager",
        "you_don't_have_any_notification": "Je hebt geen melding",
        "offers": "Aanbiedingen",
        "cpd01": "CPD01",
        "10%_off_max_discount_is_50": "10% korting Max korting is 50",
        "valid_till_:_13,June_2021": "geldig t/m : 13 juni 2021",
        "use_code": "Gebruik code",
        "passbook": "bankboekje",
        "no_wallet_history": "Geen portemonnee-geschiedenis",
        "past_trip_details": "Eerdere reisdetails",
        "pay_via": "Betalen via",
        "comments": "Opmerkingen",
        "no_comments": "Geen reacties",
        "view_receipt": "Bekijk bon",
        "dispute": "Onenigheid",
        "you": "Jij",
        "driver_unprofessional": "Bestuurder onprofessioneel",
        "open": "OPEN",
        "payment": "Betaling",
        "payment_options": "Betalingsmogelijkheden",
        "by_cash": "Contant",
        "profile": "Profiel",
        "service": "Onderhoud",
        "looking_to_change_password": "Op zoek naar wachtwoord wijzigen",
        "save": "Opslaan",
        "setting": "instelling",
        "choose_language": "Kies een taal",
        "summary": "Zomers",
        "total_no_of_rides": "Totaal aantal rijders",
        "revenue": "Omzet",
        "no._of_scheduled_rides": "Aantal geplande ritten",
        "cancelled_ride": "Geannuleerde rit",
        "wallet": "Portemonnee",
        "your_wallet_amount": "Uw Wallet-bedrag",
        "transaction_id": "Transactie ID",
        "date": "Datum",
        "your_trips": "Uw reizen",
        "add_tall_charge": "Hoge kosten toevoegen",
        "add_Toll": "Tol toevoegen",
        "dismiss": "Afwijzen",
        "please_enter_valid_amount": "Voer een geldig bedrag in",
        "please_confirm_the_address": "Bevestig het adres a.u.b",
        "picked_up_location": "Opgehaalde locatie",
        "drop_location": "Plaats neerzetten",
        "confirm": "Bevestigen",
        "otp_verification": "OTP-verificatie",
        "cancel": "Annuleren",
        "reason_for_canceling": "Reden of opzegging",
        "something_went_wrong": "Er is iets fout gegaan...",
        "scan_the_qr_to_fetch_mobile_number":
            "Scan de QR om het mobiele nummer op te halen",
        "otp_verified": "OTP geverifieerd!",
        "invoice": "Factuur",
        "booking_id": "Boekings-ID",
        "time_taken": "Tijd genomen",
        "base_fare": "Basistarief",
        "time_fare": "Tijdtarief",
        "tax": "Belasting",
        "toll_charges": "Tolkosten",
        "round_off": "Afronden",
        "total": "Totaal",
        "payable": "te betalen",
        "close": "Dichtbij",
        "time_remaining": "Time Remaining",
        "pick_up_location": "Ophaalplaats",
        "decline": "Afwijzen",
        "accept": "Aanvaarden",
        "confirm_payment": "Bevestig betaling",
        "no_data_found": "Geen data gevonden..",
        "ratings_your_trip_with": "Beoordeelt uw reis met",
        "write_your_comment": "Schrijf je commentaar",
        "are_you_sure_want_to_cancel_this_request":
            "Weet u zeker dat u dit verzoek wilt annuleren?",
        "arrived": "aangekomen",
        "picked_up": "Opgepikt",
        "arrived_location": "Aangekomen locatie",
        "waiting_time": "Wachttijd",
        "tap_when_dropped": "TIK WANNEER UITGEVALLEN",
        "hey_checkout_this_app": "Hey Check deze app, Mozlit Driver",
        "are_you_sure_want_to_logout": "Weet u zeker dat u wilt uitloggen?",
        "no": "Nee",
        "yes": "Ja",
        "add_card_for_payments": "Kaart toevoegen voor betalingen",
        "card_number": "Kaartnummer",
        "mozilit_driver": "Mozilit-stuurprogramma",
        "expiration_date": "vervaldatum",
        "cvv": "CVV",
        "add_card": "Voeg een kaart toe",
        "please_insert_valid_expiry_date": "Voer een geldige vervaldatum in",
        "change_password": "Change Password",
        "current_password": "huidig \u200B\u200Bwachtwoord",
        "terms_Condition": "Algemene voorwaarden Wachtwoord",
        "chat": "Chatten",
        "loading": "Bezig met laden...",
        "type_something_here": "Typ hier iets",
        "swipe_to_online": "Veeg naar online",
        "swipe_to_offline": "Veeg naar offline",
        "could_not_launch": "Kan niet starten",
        "qr_scan": "Qr-scan",
        "your_tips": "Uw tips",
        "earning": "Verdienen",
        "card": "Kaart",
        "share": "Deel",
        "logout": "Uitloggen",
        "ride_updated": "Rit bijgewerkt"
      },
      "es_SP": {
        "language": "Inglés",
        "Login With Password": "Iniciar sesión con contraseña",
        "payment_confirm": "su transacción está en proceso por favor espere un momento",
        "forget_password": "Has olvidado tu contraseña",
        "total_km_distance": "Distancia total en km",
        "otp": "OTP",
        "new_password": "Nueva contraseña",
        "confirm_new_password": "Confirmar nueva contraseña",
        "submit": "Entregar",
        "please_enter_otp": "Por favor ingrese OTP",
        "wrong_otp": "OTP incorrecta!",
        "please_enter_password": "Por favor, ingrese contraseña",
        "password_length": "La longitud de la contraseña debe tener entre 6 y 15 caracteres.",
        "password_should_be_same": "La contraseña debe ser la misma",
        "welcome_back": "Bienvenido de nuevo",
        "email": "Correo electrónico",
        "password": "Contraseña",
        "forget_password?": "Contraseña olvidada?",
        "log_in": "Acceso",
        "don't_have_an_account?": "no tengo una cuenta?",
        "register": "Registro",
        "enter_phone_number_to_continue": "Introduce el número de teléfono para continuar",
        "continue": "Continuar",
        "please_enter_valid_otp": "Ingrese una entrada válida",
        "didn`t_get_the_otp": "No obtuve el OTP",
        "resend_otp": "Reenviar OTP",
        "vehicle_details": "Detalles del vehículo",
        "phone": "Teléfono",
        "please_enter_your_mobile_number": "Por favor, introduzca su número de móvil.",
        "check_fare": "Consultar tarifa",
        "Book_a_ride": "reservar un viaje",
        "Schedule_a_ride": "programar un viaje",
        "sign_up": "Inscribirse",
        "or_continue_with": "O continuar con",
        "create_account": "Crear una cuenta",
        "create_an_account": "Crea una cuenta",
        "first_name": "Nombre de pila",
        "Lastname": "Apellido",
        "next": "Próximo",

        "service_type": "Tipo de servicio",
        "please_choose_a_service_type": "Por favor elige un tipo de servicio",
        "confirm_password": "confirmar Contraseña",
        "referral_code": "código de referencia",
        "referral_code_(Optional)": "Código de Referencia (Opcional)",
        "i_have_read_and_agreed_the_terms_and_Conditions":
        "He leído y acepto los Términos y Condiciones.",
        "document": "Documento",
        "data_not_found": "Datos no encontrados...",
        "edit": "Editar",
        "add": "Agregar",
        "add_document": "Agregar documento",
        "earnings": "Ganancias",
        "today's_completed_target": "Objetivo completado de hoy",
        "total_earning": "Ganancia total",
        "km": "KM",
        "total_trips": "Viajes totales",
        "time": "Tiempo",
        "distance": "Distancia",
        "amount": "Cantidad",
        "help": "Ayuda",
        "support": "Apoyo",
        "call": "Llamar",
        "message": "Mensaje",
        "our_team_persons_will_contact_you_soon!":
        "Los miembros de nuestro equipo se pondrán en contacto con usted pronto.!",
        "instant_ride": "Paseo instantáneo",
        "done": "Hecho",
        "phone_number": "Número de teléfono",
        "where_to": "A donde",
        "pick_from_map": "Seleccionar del mapa",
        "location_permissions_are_denied": "Los permisos de ubicación están denegados",
        "allow": "Permitir",
        "invite_friend": "Invitar a un amigo",
        "your_referral_code": "Su código de referencia",
        "choose_one": "elige uno",
        "referral_count:": "Recuento de referencias:",
        "referral_amount:": "Cantidad de referencia:",
        "nio_demo": "Nio Demostración",
        "from_to": "Desde Hasta",
        "round_trip": "Ida y vuelta",
        "notification_manager": "Administrador de notificaciones",
        "you_don't_have_any_notification": "no tienes ninguna notificación",
        "offers": "ofertas",
        "cpd01": "CPD01",
        "10%_off_max_discount_is_50": "10% de descuento El descuento máximo es 50",
        "valid_till_:_13,June_2021": "Válido hasta: 13 de junio de 2021",
        "use_code": "Código de uso",
        "passbook": "libreta de depósitos",
        "no_wallet_history": "Sin historial de billetera",
        "past_trip_details": "Detalles de viajes anteriores",
        "pay_via": "Pagar a través de",
        "comments": "Comentarios",
        "no_comments": "Sin comentarios",
        "view_receipt": "Ver recibo",
        "dispute": "Disputar",
        "you": "Tú",
        "driver_unprofessional": "Conductor no profesional",
        "open": "ABIERTO",
        "payment": "Pago",
        "payment_options": "Opciones de pago",
        "by_cash": "En efectivo",
        "profile": "Perfil",
        "service": "Servicio",
        "looking_to_change_password": "Buscando cambiar contraseña",
        "save": "Ahorrar",
        "setting": "Configuración",
        "choose_language": "Elige lengua",
        "summary": "Resumen",
        "total_no_of_rides": "Número total de viajes",
        "revenue": "Ganancia",
        "no._of_scheduled_rides": "Número de viajes programados",
        "cancelled_ride": "Viaje cancelado",
        "wallet": "Billetera",
        "your_wallet_amount": "El monto de su billetera",
        "transaction_id": "ID de transacción",
        "date": "Fecha",
        "your_trips": "tus viajes",
        "add_toll_charge": "Agregar cargo de peaje",
        "add_Toll": "Añadir peaje",
        "dismiss": "Despedir",
        "please_enter_valid_amount": "Por favor ingrese una cantidad válida",
        "please_confirm_the_address": "por favor_confirme la dirección",
        "picked_up_location": "Lugar de recogida",
        "drop_location": "Ubicación de entrega",
        "confirm": "Confirmar",
        "otp_verification": "Verificación OTP",
        "cancel": "Cancelar",
        "reason_for_canceling": "Razón o cancelación",
        "something_went_wrong": "Algo salió mal...",
        "scan_the_qr_to_fetch_mobile_number":
        "Escanea el QR para obtener el número de móvil",
        "otp_verified": "OTP verificado!",
        "invoice": "Factura",
        "booking_id": "ID de reserva",
        "time_taken": "Tiempo tomado",
        "base_fare": "Tarifa base",
        "time_fare": "Tarifa horaria",
        "tax": "Impuesto",
        "toll_charges": "Peajes",
        "round_off": "Redondear",
        "total": "Total",
        "payable": "Pagadero",
        "close": "Cerca",
        "time_remaining": "Tiempo restante",
        "pick_up_location": "Lugar de recogida",
        "decline": "Rechazar",
        "accept": "Aceptar",
        "confirm_payment": "Confirmar pago",
        "no_data_found": "Datos no encontrados..",
        "ratings_your_trip_with": "Califica tu viaje con",
        "write_your_comment": "Escribe tu comentario",
        "are_you_sure_want_to_cancel_this_request":
        "¿Estás seguro de que deseas cancelar esta solicitud??",
        "arrived": "Llegó",
        "picked_up": "Recogido",
        "arrived_location": "Ubicación de llegada",
        "waiting_time": "Tiempo de espera",
        "tap_when_dropped": "TOQUE CUANDO SE CAE",
        "hey_checkout_this_app": "Oye, echa un vistazo a esta aplicación, Arby Driver",
        "are_you_sure_want_to_logout": "¿Estás seguro de que quieres cerrar sesión??",
        "no": "NO",
        "yes": "Sí",
        "add_card_for_payments": "Agregar tarjeta para pagos",
        "card_number": "Número de tarjeta",
        "mozilit_driver": "Conductor Arby",
        "expiration_date": "Fecha de caducidad",
        "cvv": "CVV",
        "add_card": "Agregar tarjeta",
        "please_insert_valid_expiry_date": "Por favor, inserte una fecha de caducidad válida",
        "change_password": "Cambiar la contraseña",
        "current_password": "Contraseña actual",
        "terms_Condition": "Términos y condiciones Contraseña",
        "chat": "Charlar",
        "loading": "Cargando...",
        "type_something_here": "Escriba algo aquí",
        "swipe_to_online": "Pase a en línea",
        "swipe_to_offline": "Deslizar para desconectarse",
        "could_not_launch": "no se pudo iniciar",
        "qr_scan": "Escaneo qr",
        "your_tips": "Tus consejos",
        "earning": "Ganador",
        "card": "Tarjeta",
        "share": "Compartir",
        "logout": "Cerrar sesión",
        "ride_updated": "Paseo actualizado",
        "hi": "Hola",
        "past_rides": "Paseos pasados",
        "account": "Cuenta",
        "source": "Fuente",
        "destination": "Destino",
        "user_arrogant_and_rude": "Usuario arrogante y grosero",
        "charging_stations": "Estaciones de carga",
        "give_feedback": "Dar opinion",
        "terms_and_conditions": "Términos y condiciones",
        "privacy_policy": "política de privacidad",
        "our_you_soon!": "Nuestro miembro del equipo se pondrá en contacto con usted pronto!",
        "add_money": "Agregar dinero",
        "add_amount": "Añadir cantidad",
        "together": "Juntos, estamos creciendo Más fuerte y más lejos",
        "refer_now_and_earn": "Refiera ahora y gane",
        "or": "O",
        "share_your_link_via": "Comparte tu enlace a través de",
        "spread_the_word": "Corre la voz, y te recompensaremos",
        "get INR 100 in your Eto wallet for every friend you refer":
        "Obtén INR 100 en tu billetera Eto por cada amigo que refieras",
        "refCode:": "código de referencia:",
        "delete_account": "Borrar cuenta",
        "trip_details": "Detalles del viaje",
        "start_ride": "Iniciar viaje",
        "end_ride": "Finalizar viaje",
        "feedback_for_the_user": "Comentarios para el usuario",
        "Please_type_the_verification_code_sent_to_your":
        "Por favor, escriba el código de verificación enviado a su",
        "mobile_number": " Número de teléfono móvil",
        "your_email": " Correo electrónico",
        "verification_code": "Código de verificación",
        "forgot_password": "Has olvidado tu contraseña",
        "Driver_Registration": "Registro de conductor",
        "Vehicle_Registration": "Registro de Vehículo",
        "did_get_the_OTP": "no obtuve la OTP?",
        "look_for_new_ride": "Busque un nuevo viaje",
        "car_type": "Tipo de carro",
        "car_name": "Nombre del coche",
        "car_color": "Color del coche",
        "car_model": "Modelo de auto",
        "car_number": "Número de coche",
        "please_enter_amount": "Por favor ingrese la cantidad",
        "Please_enter_more_when_amount": "Ingrese más cuando la cantidad",
        "sorry_for_inconvenience_time_Our_partner": "Lo siento por el tiempo de inconveniencia, nuestro socio o ocupado. Inténtalo después de un tiempo.",
        "We_are_searching_for_new_driver_please_wait_till_we_get_the_new_driver": "Estamos buscando un nuevo controlador, espere hasta que obtengamos el nuevo controlador.",
      },
      "ar_AE": {
        "language": " إنجليزي ",
        "log_in": "تسجيل الدخول",
        "Driver_Registration": "تسجيل السائق",
        "first_name": "الاسم الأول",
        "Lastname": "اسم العائلة",
        "next": "التالي",
        "login": "تسجيل الدخول",
        "Login With Password": "تسجيل الدخول بكلمة مرور",
        "forget_password": " هل نسيت كلمة السر ",
        "otp": "OTP",
        "new_password": " كلمة السر الجديدة ",
        "confirm_new_password": " تأكيد كلمة المرور الجديدة ",
        "submit": " يُقدِّم ",
        "please_enter_otp": " الرجاء إدخال OTP ",
        "wrong_otp": " OTP خاطئ!",
        "please_enter_password": " الرجاء إدخال كلمة المرور ",
        "password_length": " يجب أن يتراوح طول كلمة المرور بين 6-15 حرفًا.",
        "password_should_be_same": " يجب أن تكون كلمة المرور هي نفسها ",
        "welcome_back": " مرحبًا بعودتك ",
        "email": " البريد الإلكتروني ",
        "password": " كلمة المرور ",
        "forget_password?": " نسيت كلمة المرور؟",
        "log_in": " تسجيل الدخول ",
        "don't_have_an_account?": " ليس لديك حساب؟",
        "register": " يسجل ",
        "enter_phone_number_to_continue": " أدخل رقم الهاتف للمتابعة ",
        "please_type_the_verification_code_sent_to_your":
        " الرجاء كتابة رمز التحقق \ المرسل إلى الخاص بك ",
        "continue": " يكمل ",
        "please_enter_valid_otp": " الرجاء إدخال otp In صالح ",
        "didn`t_get_the_otp": "لم أحصل على OTP",
        "resend_otp": "إعادة إرسال OTP",
        "phone": " هاتف ",
        "please_enter_your_mobile_number": " الرجاء إدخال رقم هاتفك المحمول.",
        "check_are": " تحقق من الأجرة ",
        "sign_up": " اشتراك ",
        "or_continue_with": " أو تواصل مع ",
        "create_account": " إصنع حساب ",
        "firstname": " الاسم الاول ",
        "Lastname": " الكنية ",
        "car_model": " طراز السيارة ",
        "car_number": " رقم السياره ",
        "service_type": " نوع الخدمة ",
        "please_choose_a_service_type": " الرجاء اختيار نوع الخدمة ",
        "confirm_password": " تأكيد كلمة المرور ",
        "referral_code": " كود الإحالة ",
        "referral_code_(Optional)": " إحالة قانون (اختياري)",
        "i_have_read_and_agreed_the_terms_and_Conditions":
        " لقد قرأت ووافقت على الشروط والأحكام. ",
        "document": " وثيقة ",
        "data_not_found": " لم يتم العثور على بيانات...",
        "edit": " يحرر ",
        "add": " يضيف ",
        "add_document": " أضف وثيقة ",
        "earnings": " أرباح ",
        "today's_completed_target": " الهدف المكتمل اليوم ",
        "total_earning": " مجموع الأرباح ",
        "km": "KM",
        "total_trips": " إجمالي الرحلات ",
        "time": " زمن ",
        "distance": " مسافه: بعد ",
        "amount": " مقدار ",
        "help": " مساعدة ",
        "support": " الدعم ",
        "call": " مكالمة ",
        "message": " رسالة ",
        "our_team_persons_will_contact_you_soon!":
        " سيتصل بك أفراد فريقنا قريبًا!",
        "instant_ride": " رحلة فورية ",
        "done": " فعله ",
        "phone_number": " رقم الهاتف ",
        "where_to": " إلى أين ",
        "pick_from_map": " اختر من الخريطة ",
        "location_permissions_are_denied": " تم رفض أذونات الموقع ",
        "allow": " السماح ",
        "invite_friend": " قم بدعوة صديق ",
        "your_referral_code": " رمز الإحالة الخاص بك ",
        "choose_one": " اختر واحدة ",
        "referral_count_:": " عدد الإحالة ",
        "referral_amount:": " مبلغ الإحالة ",
        "nio_demo": " نيو ديمو ",
        "from_to": " من الى ",
        "round_trip": " ذهابا وإيابا ",
        "notification_manager": " مدير الإعلام ",
        "you_don't_have_any_notification": " ليس لديك أي إخطار ",
        "offers": " عروض ",
        "cpd01": " CPD01",
        "10%_off_max_discount_is_50": "10٪ خصم الحد الأقصى للخصم 50",
        "valid_till_:_13,June_2021": " صالح حتى: 13 يونيو 2021",
        "use_code": " استخدم الكود ",
        "passbook": " وصل الدفع ",
        "no_wallet_history": " لا يوجد محفوظات المحفظة ",
        "past_trip_details": " تفاصيل الرحلة السابقة ",
        "pay_via": " الدفع عن طريق ",
        "comments": " تعليقات ",
        "no_comments": " لا تعليق ",
        "view_receipt": " استلام عرض ",
        "dispute": " خلاف ",
        "you": " أنت ",
        "driver_unprofessional": " سائق غير محترف ",
        "open": " افتح ",
        "payment": " دفع ",
        "payment_options": " خيارات الدفع ",
        "by_cash": " نقدا ",
        "profile": " الملف الشخصي ",
        "service": " خدمة ",
        "looking_to_change_password": " تبحث لتغيير كلمة المرور ",
        "save": " يحفظ ",
        "setting": " ضبط ",
        "choose_language": " اختر اللغة ",
        "summary": " ملخص ",
        "total_no_of_rides": " العدد الإجمالي للجولات ",
        "revenue": " ربح ",
        "no._of_scheduled_rides": " عدد الرحلات المجدولة ",
        "cancelled_ride": " رحلة ملغاة ",
        "wallet": " محفظة ",
        "your_wallet_amount": " مبلغ محفظتك ",
        "transaction_id": " رقم المعاملة ",
        "date": " تاريخ ",
        "your_trips": " رحلاتك ",
        "add_toll_charge": " إضافة رسوم ",
        "add_Toll": " أضف رسوم ",
        "dismiss": " رفض ",
        "please_enter_valid_amount": " الرجاء إدخال مبلغ صالح ",
        "please_confirm_the_address": " يرجى تأكيد العنوان ",
        "picked_up_location": " التقطت الموقع ",
        "drop_location": " إسقاط الموقع ",
        "confirm": " يتأكد ",
        "otp_verification": " التحقق من OTP ",
        "cancel": " يلغي ",
        "reason_for_canceling": " السبب أو الإلغاء ",
        "something_went_wrong": " هناك خطأ ما...",
        "scan_the_qr_to_fetch_mobile_number":
        " امسح QR لجلب رقم الهاتف المحمول ",
        "otp_verified": " تم التحقق من OTP!",
        "invoice": " فاتورة ",
        "booking_id": " معرف الحجز ",
        "time_taken": " الوقت المستغرق ",
        "base_fare": " الاجرة الاساسية ",
        "time_fare": " أجرة الوقت ",
        "tax": " ضريبة ",
        "toll_charges": " رسوم لعبور ",
        "round_off": " نهاية الجولة ",
        "total": " المجموع ",
        "payable": " مستحق الدفع ",
        "close": " قريب ",
        "time_remaining": " الوقت المتبقي ",
        "pick_up_location": " اختر موقعا ",
        "decline": " انخفاض ",
        "accept": " قبول ",
        "confirm_payment": " تأكيد الدفع ",
        "no_data_found": " لاتوجد بيانات..",
        "ratings_your_trip_with": " تقييمات رحلتك مع ",
        "write_your_comment": " اكتب تعليقك ",
        "are_you_sure_want_to_cancel_this_request":
        " هل أنت متأكد من أنك تريد إلغاء هذا الطلب?",
        "arrived": " وصل ",
        "picked_up": " التقط ",
        "arrived_location": " وصل الموقع ",
        "waiting_time": " وقت الانتظار ",
        "tap_when_dropped": " اضغط عند السقوط ",
        "hey_checkout_this_app": " مرحبًا ، تحقق من هذا التطبيق ، سائق Mozlit ",
        "are_you_sure_want_to_logout":
        " هل أنت متأكد من أنك تريد تسجيل الخروج?",
        "no": " رقم ",
        "yes": " نعم ",
        "add_card_for_payments": " إضافة بطاقة للمدفوعات ",
        "card_number": " رقم البطاقة ",
        "mozilit_driver": " سائق Mozilit ",
        "expiration_date": " تاريخ إنتهاء الصلاحية ",
        "cvv": "CVV",
        "add_card": " إضافة بطاقة ",
        "please_insert_valid_expiry_date": " الرجاء إدخال تاريخ انتهاء صالح ",
        "change_password": " غير كلمة السر ",
        "current_password": " كلمة المرور الحالية ",
        "terms_Condition": " كلمة مرور الشروط والأحكام ",
        "terms_and_Condition": " الشروط والأحكام ",
        "chat": " دردشة ",
        "loading": " جار التحميل...",
        "type_something_here": " اكتب شيئًا هنا ",
        "swipe_to_online": " مرر سريعًا للانتقال إلى الإنترنت ",
        "swipe_to_offline": " مرر سريعًا للانتقال إلى وضع عدم الاتصال ",
        "could_not_launch": " تعذر الإطلاق ",
        "qr_scan": " Qr Scan ",
        "your_tips": " نصائحك ",
        "earning": " كسب ",
        "card": " بطاقة ",
        "share": " يشارك ",
        "logout": " تسجيل خروج ",
        "settings": "الإعدادات",
        "account":"الحساب",
        "past_rides": "الرحلات الماضية",
        "invite_a_friend": "أدع صديقا",
        "Taxi service type": "نوع خدمة سيارات الأجرة",
        "Delivery service type": "نوع خدمة التوصيل",
        "TAXI": "سيارة اجره",
        "DELIVERY": "توصيل",
        "package_details": "حزمة من التفاصيل",
        "congratulations": "تهانينا",
        "you_have_successfully": "لقد نجحت",
        "completed": "مكتمل",
        "trips_with": "رحلات مع",
        "touk_touk": "طوق طوك",
        "you_are_now_a_verified": "أنت الآن سائق معتمد على Touk Touk",
        "All_users_will": "سيتمكن جميع المستخدمين من رؤية ملف",
        "verification_green_tick": "التحقق من العلامة الخضراء",
        "in_front_of_your_name": "امام اسمك",
        "keep_Riding": "استمر في القيادة معنا ، نحن نقدر ثقتكم بنا",
        "taxi": 'سيارة اجره',
        "delivery": "توصيل"
      },
      "hy_AM": {
        "language": " Անգլերեն ",
        "log_in": "Մուտք գործեք",
        "Driver_Registration": "Վարորդի գրանցում",
        "first_name": "Անուն",
        "last_name": "Ազգանուն",
        "next": "Հաջորդը",
        "Login": "մուտք",
        "Login With Password": "Մուտք գործել Գաղտնաբառով",
        "forget_password": " Մոռացել եք գաղտնաբառը ",
        "otp": "OTP",
        "new_password": " նոր ծածկագիր ",
        "confirm_new_password": " Հաստատեք նոր գաղտնաբառը ",
        "submit": " Ներկայացնել ",
        "please_enter_otp": " Խնդրում ենք մուտքագրել OTP ",
        "wrong_otp": " Սխալ OTP!",
        "please_enter_password": " Խնդրում ենք մուտքագրել գաղտնաբառը ",
        "password_length": " Գաղտնաբառի երկարությունը պետք է լինի 6-15 նիշ.",
        "password_should_be_same": " Գաղտնաբառը պետք է լինի նույնը ",
        "welcome_back": " Բարի վերադարձ ",
        "email": " Էլ ",
        "password": " Գաղտնաբառ ",
        "forget_password?": " Մոռացեք գաղտնաբառը?",
        "don't_have_an_account?": " Չունե՞ք հաշիվ:",
        "register": " Գրանցվել ",
        "enter_phone_number_to_continue":
        " Շարունակելու համար մուտքագրեք հեռախոսահամարը ",
        "please_type_the_verification_code_sent_to_your":
        " Խնդրում ենք մուտքագրել հաստատման կոդը\ուղարկված է ձեզ ",
        "continue": " Շարունակել ",
        "please_enter_valid_otp": " Խնդրում ենք մուտքագրել վավեր otp In ",
        "didn`t_get_the_otp": " Չեմ ստացել OTP ",
        "resend_otp": " ՎԵՐԱՍԱՐԿԵԼ OTP-ը ",
        "phone": " Հեռախոս ",
        "please_enter_your_mobile_number":
        " Խնդրում ենք մուտքագրել ձեր բջջային համարը.",
        "check_are": " Ստուգեք ուղեվարձը ",
        "sign_up": " Գրանցվել ",
        "or_continue_with": " Կամ Շարունակեք ",
        "create_account": " Գրանցվել ",
        "firstname": " Անուն ",
        "last_name": " Ազգանուն ",
        "car_model": " Ավտոմեքենայի մոդել ",
        "car_number": " Մեքենայի համարը ",
        "service_type": " Ծառայության տեսակը ",
        "please_choose_a_service_type":
        " Խնդրում ենք ընտրել ծառայության տեսակը ",
        "confirm_password": " Հաստատել գաղտնաբառը ",
        "referral_code": " Ուղղորդման Կոդ ",
        "referral_code_(Optional)": " Ուղղորդման կոդ (ըստ ցանկության)",
        "i_have_read_and_agreed_the_terms_and_Conditions":
        " Ես կարդացել և համաձայն եմ Պայմաններն ու Պայմանները.",
        "document": " Փաստաթուղթ ",
        "data_not_found": " Տվյալները չեն գտնվել...",
        "edit": " Խմբագրել ",
        "add": " Ավելացնել ",
        "add_document": " Ավելացնել փաստաթուղթ ",
        "earnings": " Շահույթ ",
        "today's_completed_target": " Այսօրվա ավարտված նպատակը ",
        "total_earning": " Ընդհանուր եկամուտ ",
        "km": "KM",
        "total_trips": " Ընդհանուր Ուղևորություններ ",
        "time": " Ժամանակը ",
        "distance": " Հեռավորությունը ",
        "amount": " Գումարը ",
        "help": " Օգնություն ",
        "support": " Աջակցություն ",
        "call": " Զանգահարեք ",
        "message": " Հաղորդագրություն ",
        "our_team_persons_will_contact_you_soon!":
        " Մեր թիմի աշխատակիցները շուտով կկապվեն ձեզ հետ!",
        "instant_ride": " Ակնթարթային զբոսանք ",
        "done": " Կատարած ",
        "phone_number": " Հեռախոսահամար ",
        "where_to": " Ուր Դեպի ",
        "pick_from_map": " Ընտրեք քարտեզից ",
        "location_permissions_are_denied":
        " Տեղադրության թույլտվությունները մերժված են ",
        "allow": " Թույլատրել ",
        "invite_friend": " Հրավիրեք ընկերոջը ",
        "your_referral_code": " Ձեր ուղղորդման կոդը ",
        "choose_one": " Ընտրիր մեկը ",
        "referral_count_:": " Ուղղորդման հաշվարկ:",
        "referral_amount:": " Ուղղորդման գումարը:",
        "nio_demo": " Nio Demo ",
        "from_to": "From To",
        "round_trip": " Շրջագայություն ",
        "notification_manager": " Ծանուցումների կառավարիչ ",
        "you_don't_have_any_notification": " Դուք որևէ ծանուցում չունեք ",
        "offers": " Առաջարկներ ",
        "cpd01": "CPD01",
        "10%_off_max_discount_is_50":
        "10% զեղչ Առավելագույն զեղչը կազմում է 50",
        "valid_till_:_13,June_2021":
        " ուժի մեջ է մինչև 2021 թվականի հունիսի 13-ը",
        "use_code": " Օգտագործեք կոդը ",
        "passbook": " անձնագիրք ",
        "no_wallet_history": " Դրամապանակի պատմություն չկա ",
        "past_trip_details": " Անցյալ ուղևորության մանրամասները ",
        "pay_via": " Վճարեք միջոցով ",
        "comments": " Մեկնաբանություններ ",
        "no_comments": " Առանց մեկնաբանությունների ",
        "view_receipt": " Դիտել անդորրագիրը ",
        "dispute": " վեճ",
        "you": " Դուք ",
        "driver_unprofessional": " Վարորդը ոչ պրոֆեսիոնալ ",
        "open": " ԲԱՑ ",
        "payment": " Վճարում ",
        "payment_options": " Վճարման տարբերակներ ",
        "by_cash": " Կանխիկով ",
        "profile": " Անձնագիր ",
        "service": " Ծառայություն ",
        "looking_to_change_password": " Փնտրում եմ փոխել գաղտնաբառը ",
        "save": " Պահպանել ",
        "setting": " Կարգավորում ",
        "choose_language": " Ընտրեք Լեզուն ",
        "summary": " Ամփոփում ",
        "total_no_of_rides": " Ուղևորությունների ընդհանուր թիվը ",
        "revenue": " Եկամուտներ ",
        "no._of_scheduled_rides": " Պլանավորված ուղևորությունների թիվ ",
        "cancelled_ride": " Չեղարկված ուղևորություն ",
        "wallet": " Դրամապանակ ",
        "your_wallet_amount": " Ձեր դրամապանակի գումարը ",
        "transaction_id": " Գործարքի համար ",
        "date": " Ամսաթիվ ",
        "your_trips": " Ձեր ճամփորդությունները ",
        "add_toll_charge": " Ավելացրեք վճարովի վճար ",
        "add_Toll": " Ավելացրեք վճարովի վճարում ",
        "dismiss": " Հեռացնել ",
        "please_enter_valid_amount": " Խնդրում ենք մուտքագրել վավեր գումար ",
        "please_confirm_the_address": " խնդրում ենք հաստատել հասցեն ",
        "picked_up_location": " Վերցված գտնվելու վայրը ",
        "drop_location": " Թողնել տեղադրությունը ",
        "confirm": " Հաստատել ",
        "otp_verification": " OTP ստուգում ",
        "cancel": " Չեղարկել ",
        "reason_for_canceling": " Պատճառը կամ չեղարկումը ",
        "something_went_wrong": " Ինչ որ բան այնպես չգնաց...",
        "scan_the_qr_to_fetch_mobile_number":
        " Սկանավորեք QR-ը՝ բջջային համարը ստանալու համար ",
        "otp_verified": " OTP Ստուգված!",
        "invoice": " Հաշիվ-ապրանքագիր ",
        "booking_id": " Ամրագրման ID ",
        "time_taken": " Վերցված ժամանակ ",
        "base_fare": " Հիմնական ուղեվարձը ",
        "time_fare": " Ժամանակի ուղեվարձ ",
        "tax": " Հարկային ",
        "toll_charges": " Վճարներ ",
        "round_off": " Շուրջը ",
        "total": " Ընդամենը ",
        "payable": " Վճարվող ",
        "close": " փակել ",
        "time_remaining": " Մնացած ժամանակը ",
        "pick_up_location": " Վերցնելու գտնվելու վայրը ",
        "decline": " Անկում ",
        "accept": " Ընդունել ",
        "confirm_payment": " Հաստատեք վճարումը ",
        "no_data_found": " Տվյալներ չեն գտնվել..",
        "ratings_your_trip_with": " Գնահատում է ձեր ճանապարհորդությունը ",
        "write_your_comment": " Գրեք ձեր մեկնաբանությունը ",
        "are_you_sure_want_to_cancel_this_request":
        " Իսկապե՞ս ուզում եք չեղարկել այս հարցումը?",
        "arrived": " Ժամանել է ",
        "picked_up": "Վերցրեց ",
        "arrived_location": " Ժամանած գտնվելու վայրը ",
        "waiting_time": " Սպասման ժամանակ ",
        "tap_when_dropped": " ԹԱԿԵՔ, ԵՐԲ ԸՆԹԱՑՎԻ ",
        "hey_checkout_this_app": " Ստուգեք այս հավելվածը, Mozlit Վարորդ ",
        "are_you_sure_want_to_logout": " Իսկապե՞ս ուզում եք դուրս գալ?",
        "no": " ՈՉ ",
        "yes": " Այո՛ ",
        "add_card_for_payments": " Ավելացրեք քարտ վճարումների համար ",
        "card_number": " Քարտի համար ",
        "mozilit_driver": " Mozilit վարորդ ",
        "expiration_date": " Սպառման ամսաթիվ ",
        "cvv": "CVV",
        "add_card": "Add Card",
        "please_insert_valid_expiry_date":
        " Խնդրում ենք մուտքագրել վավեր ժամկետը ",
        "change_password": " Փոխել գաղտնաբառը ",
        "current_password": " Ընթացիկ գաղտնաբառը ",
        "terms_Condition": " Պայմաններ և դրույթներ Գաղտնաբառ ",
        "terms_and_Condition": " Պայմաններ և դրույթներ ",
        "chat": " Զրուցարան ",
        "loading": " Բեռնվում է...",
        "type_something_here": " Մուտքագրեք ինչ-որ բան այստեղ ",
        "swipe_to_online": " Սահեցրեք՝ առցանց գնալու համար ",
        "swipe_to_offline": " Անցանց գնալու համար սահեցրեք ",
        "could_not_launch": " Չհաջողվեց գործարկել ",
        "qr_scan": "Qr սկան",
        "your_tips": " Ձեր խորհուրդները ",
        "earning": " Վաստակել ",
        "card": " Քարտ ",
        "share": " Կիսվել ",
        "logout": " Դուրս գալ ",
        "settings": "Settings",
        "Taxi service type": "Տաքսի ծառայության տեսակը",
        "Delivery service type": "Առաքման ծառայության տեսակը",
        "TAXI": "ՏԱՔՍԻ",
        "DELIVERY": "ԱՌԱՔՈՒՄ",
        "package_details": "Փաթեթի մանրամասները",
        "congratulations": "Շնորհավորում եմ",
        "you_have_successfully": "Դուք հաջողությամբ",
        "completed": "ավարտված",
        "trips_with": "հետ ճամփորդություններ",
        "touk_touk": "Թուկ Թուկ",
        "you_are_now_a_verified": "Դուք այժմ ստուգված վարորդ եք Touk Touk-ում",
        "All_users_will": "Բոլոր օգտվողները կկարողանան տեսնել",
        "verification_green_tick": "Ստուգման կանաչ տիզ",
        "in_front_of_your_name": "քո անվան դիմաց",
        "keep_Riding": "Շարունակեք վարել մեզ հետ, մենք գնահատում ենք ձեր վստահությունը, որը դրված է մեզ վրա",
        "taxi": "տաքսի",
        "delivery": "առաքում"
      }
    };
  }
}
